---
title: "Ruth Schmidt's Resume"
author: Ruth L. Schmidt
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: custom_resume.css
uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print

---

```{css, echo=FALSE}
a {
  color: #008B8B;
}

.pagedjs_page:not(:first-of-type) {
  background: white;
}

.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}

.pagedjs_page {
  --sidebar-width: 14.5rem;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
}
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-home"></i> 5932 Avenue de L'Esplanade, H2T3A3 Montréal, Canada
- <i class="fa fa-phone"></i> +1 438-979-8112
- <i class="fa fa-envelope"></i> schmidt.ruth@gmail.com
- <i class="fa fa-linkedin"></i> [linkedin.com/ruth-schmidt/](https://www.linkedin.com/in/ruth-schmidt/)
- <i class="fa fa-globe"></i> [ruthlydiaschmidt.com](https://ruthlydiaschmidt.com/)


Technical Skills {#skills}
--------------------------------------------------------------------------------

- <i class="fas fa-laptop"></i> R, Dash & Dash Bio (Plotly), Python, UNIX, Markdown, SQL, CSS & HTML 
- <i class="fas fa-chart-bar"></i> Multivariate statistics, <br> statistical models
- <i class="fas fa-dna"></i> Molecular biology techniques, Omic technologies & data analysis
- <i class="fas fa-broom"></i> Data cleaning, processing, <br> manipulation & visualization

Interpersonal Skills {#skills}
--------------------------------------------------------------------------------

- Excellent communicator
- Highly creative
- Problem solver
- Strong team player & collaborative
- Excellent time management
- Open-minded and adaptable

Languages {#skills}
--------------------------------------------------------------------------------

- German (Native)
- English (Fluent)
- Spanish (Advanced)
- French (Beginner) 

Main
================================================================================

Ruth Lydia Schmidt {#title}
--------------------------------------------------------------------------------

### Microbial Ecologist & Data Scientist

A dynamic and resourceful microbial ecologist with 8 years of experience in microbiome research, data analysis and science communication, with strong leadership and a broad set of technical and interpersonal skills. Passionate about finding sustainable solutions for environmental issues through the combination of research, data and policy.

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Ph.D. in Microbial Ecology

Wageningen University & Netherlands Institute of Ecology (NIOO)<br>
Title: [Volatile communication between fungi and bacteria](https://research.wur.nl/en/publications/volatile-communication-between-fungi-and-bacteria)</br>

Wageningen, The Netherlands

10/2017 

### M.S. in Biotechnology 

Graz University of Technology

Graz, Austria

12/2012

### B.Sc. in Molecular Biology 

Graz University of Technology

Graz, Austria

09/2010

Research Experience {data-icon=dna}
--------------------------------------------------------------------------------

### Mitacs Postdoctoral Fellow

Institut national de la recherche scientifique (INRS) & Plotly 

Montréal, Canada

01/2020 - Present

- Developing open-source [visualization apps for omic data in microbiome research](https://www.mitacs.ca/fr/projects/visualization-multi-omics-data-microbiome-research) using Ploty’s Dash R and Dash Bio libraries.

### Visiting JSPS Postdoctoral Fellow

Kochi Core Center

Kochi, Japan 

01/2020 - 03/2020

- Developed PCR-based screening method for detection of terpene synthase genes (TPS) across terrestrial and aquatic environments. 
- Performed amplicon sequencing of PCR products and bioinformatics data analysis. 

### Consultant

International Union for Conservation of Nature (IUCN)

remote

07/2019-10/2019

- Contributed to a global report on soil biodiversity in agro-ecosystem health.

### Postdoctoral Fellow

Institut national de la recherche scientifique (INRS), Labo Yergeau

Montréal, Canada

02/2018 - 12/2019

- Research on microbial solutions to drought in agriculture.
- Led lab and field studies with wheat under drought conditions.
- Conducted analysis of omic data (quantitative metagenomics, metatranscriptomics, metabolomics). 
- Co-supervised 4 PhD students and 2 Master students.
- Presented findings at 6 international conferences. 
- Collaborated with researchers in The Netherlands (Netherlands Institute of <br>Ecology) & UK (Plymouth Marine Laboratory). 

### PhD Candidate 

Netherlands Institute of Ecology & Wageningen University, Garbeva Group

Wageningen, The Netherlands

02/2013 - 10/2018

- Characterized molecular mechanism underlying volatile interaction in soil microbes using a combination of omic, microbiological, and analytical (GC-MS) approaches ([link to video about research](https://www.youtube.com/watch?time_continue=5&v=dnb8Sc8NXS4)).
-	Analyzed omic data (proteomics, metabolomics) and developed workflow for metabolomic data analysis. 
- Mentored 4 undergraduate and 1 graduate student on molecular biology research projects.
-	Collaborated with international research institutes and universitites in Germany (Max-Planck Institute for Chemical Ecology, Jena & Center for Functional Genomics of Microbes, Greifswald), US (Institute for Genome Sciences, Baltimore) & Sweden (Swedish University of Agricultural Sciences) on genomics and proteomics projects.

### University assistant  

Graz University of Technology

Graz, Austria

10/2010-12/2012

- Led and conducted field study on the effect of biocontrol agents in field in Egypt. 
- Performed analysis of 16S rRNA sequencing data, and measurement and analysis of analytical data (LC-MS).

Teaching Experience {data-icon=book-open}
--------------------------------------------------------------------------------

### Instructor in two days hands-on course on proteomics

Netherlands Institute of Ecology 

Wageningen, The Netherlands 

09/2015


### Teaching Assistant in Laboratory Course in Environmental Biotechnology

Graz University of Technology

Graz, Austria 

10/2013

### Research Assistant in Laboratory Course in Biochemistry and Molecular Biology

Karl-Franzens University

Graz, Austria 

06/2012

Grants & awards {data-icon=award}
--------------------------------------------------------------------------------

### Mitacs Postdoctoral Fellowship (60,000 CAD)

Visualization of multi-omics data in microbiome research

Montréal, Canada 

2019

### Japan Society for the Promotion of Science (JSPS) Award (8,000 CAD)

Uncovering microbial chemical ecology in the extreme sub-seafloor environment

Kochi Core Centre, Japan 

2019

### Coalesce BioArt residency (2,000 USD)

[Microbial Scents and Olfactory Prosthesis for the Future](https://www.buffalo.edu/genomeenvironmentmicrobiome/coalesce/projects-and-residencies1/residents/TiareRibeauxandRuthSchmidt.html)

Coalesce: Center for Biological Art, University at Buffalo, USA

2019

### Quebec Centre for Biodiversity Science (QCBS) Travel grant (1,500 CAD)

International Phytobiome meeting 

Montpellier, France 

2018

### QCBS Seed grant (5,000 CAD)

[Aural soilscapes: creating ecological consciousness to global warming](https://www.soundandspaceresearch.com/latestnews/2019/2/7/aural-soilscapes-ckjtc)

Montréal, Canada 

2018

### QCBS Travel grant (1,500 CAD)

ISME17 meeting

Leipzig, Germany

2018 

### International Society of Chemical Ecology (ISCE) Travel Grant  (1,000 USD)

Annual Meeting ISCE17

Kyoto, Japan 

2017

### Best Talk Award (150 USD)

Annual Meeting ISCE17 

Kyoto, Japan 

2017

### Federation of European Microbiological Societies (FEMS) Research Grant (5,000 Eur)

Research on fungal genomics at the Swedish University of Agricultural Sciences (SLU)

Uppsala, Sweden 

2017

### International Society for Microbial Ecology (ISME) Travel Grant (800 Eur)

ISME16 meeting 

Montréal, Canada 

2016

### FEMS Meetings Attendance Grant (300 Eur)

Ecology of Soil Microorganisms meeting

Prague, Czech Republic

2015

### Best Poster Award (100 Eur)

Ecology of Soil Microorganisms meting

Prague, Czech Republic 

2015 


Presentations {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Kochi Core Center (talk)

Uncovering microbial terpenes in the extreme sub-seafloor environment.

Kochi, Japan 

02/2020

### International Society of Chemical Ecology, ISCE 35 (talk)

Microbial chemical ecology: past, present and future. 

Atlanta, USA

06/2019

### Second International Holobiont meeting (talk)

How microbial volatiles help plants survive in times of drought.

Montréal, Canada

05/2019

### Quebec Centre for Biodiversity Science Annual Symposium (talk)

Microbial aromas might help plants survive drought. 

Montréal, Canada

12/2018

### International Phytobiomes Conference (poster)

Microbial terpenes in the plant holobiont as a strategy to adapt to drought.

Montpellier, France

12/2018

### International Symposium on Microbial Ecology, ISME 17 (talk)

Do bacteria and fungi have a fragrant language all their own?

Leipzig, Germany

08/2018

### International Symposium on Microbial Ecology, ISME 17 (speaker in roundtable session)

Microbial chemical ecology: intra- and interspecies communication.

Leipzig, Germany

08/2018

### Champalimaud Centre for the Unknown 

Microworld - the most powerful life on earth. 

Lisbon, Portugal

06/2018 

### International Society of Chemical Ecology, ISCE 34 (talk)

Terpenes as *lingua franca* between fungi and bacteria. 

Kyoto, Japan

08/2017

### International Symposium on Microbial Ecology, ISME 16 (poster)

Transcriptional responses of a beneficial soil bacterium to volatiles of a plant pathogen.

Montréal, Canada 

08/2016

### Ecology of soil microorganisms, ESM (poster) 

Microbial small talk: Volatiles in fungal-bacterial interactions. 

Prague, Czech Republic

12/2015

### 4th International student conference on Microbial Communication, MiCom (talk) 

Chemical dialogues: The ability of bacteria to sense fungal volatiles.

Jena, Germany

04/2014

### CNRS-Jacques Monod conference: bacterial–fungal interactions: a federative field for fundamental and applied microbiology

The role of fungal volatiles as signaling compounds in bacterial-fungal interactions. 

Roscoff, France

12/2013

### Boston Bacterial Meeting, BBM (poster) 

Microbial interactions via secondary metabolites in soil. 

Boston, USA

06/2013

### Netherlands Annual Ecology Meeting, NERN (poster)

The best bacterial competitive strategies in the rhizosphere. 

Lunteren, The Netherlands

02/2013

Publications {data-icon=file}
--------------------------------------------------------------------------------

### A Gaseous Milieu: Extending the Boundaries of the Rhizosphere. 
Trends in microbiology. [DOI: 10.1016/j.tim.2020.02.016](https://doi.org/10.1016/j.tim.2020.02.016)

N/A

2020

de la Porte, A., **Schmidt, R.**, Yergeau, É., & Constant, P. 

### Microbe-driven chemical ecology: past, present and future.
ISME J. [DOI: 10.1038/s41396-019-0469-x](https://doi.org/10.1038/s41396-019-0469-x)

N/A

2019

**Schmidt, R.**, Ulanova, D., Wick, L. Y., Bode, H. B., & Garbeva, P.

### Deciphering the genome and secondary metabolome of the plant pathogen *Fusarium culmorum*. 
FEMS Microbiol Ecol. [DOI: 10.1093/femsec/fiy078](https://doi.org/10.1093/femsec/fiy078)

N/A

2018 

**Schmidt, R.**, Durling, M. B., de Jager, V., Menezes, R. C., Nordkvist, E., Svatoš, A., Dubey, M., Lauterbach, L., Dickschat, J. S., Karlsson, M., & Garbeva, P.

### Fifty Percent Human - how art brings us in touch with our microbial cohabitants.
Microb Biotechnol.[DOI: 10.1111/1751-7915.13285](https://doi.org/10.1111/1751-7915.13285)

N/A 

2018 

Bäumel, S., Tytgat, H., Nemec, B., **Schmidt, R.**, Chia, L. W., & Smidt, H. 

### The future of ecology is collaborative, inclusive and deconstructs biases. 
Nat Ecol Evol. [DOI: 10.1038/s41559-017-0445-7](https://www.nature.com/articles/s41559-017-0445-7)

N/A

2018

Ramirez, K. S., Berhe, A. A., Burt, J., Gil-Romera, G., Johnson, R. F., Koltz, A. M., Lacher, I., McGlynn, T., Nielsen, K. J., **Schmidt, R.**, Simonis, J. L., terHorst, C. P., & Tuff, K.

### Fungal volatile compounds induce production of the secondary metabolite Sodorifen in *Serratia plymuthica* PRI-2C.
Sci Rep. [DOI: 10.1038/s41598-017-00893-3](https://doi.org/10.1038/s41598-017-00893-3)

N/A

2017

**Schmidt, R.**, Jager, V., Zühlke, D., Wolff, C., Bernhardt, J., Cankar, K., Beekwilder, J., Ijcken, W. V., Sleutels, F., Boer, W., Riedel, K., & Garbeva, P. 

### Controlling the Microbiome: Microhabitat Adjustments for Successful Biocontrol Strategies in Soil and Human Gut.
Front Microbiol. [DOI: 10.3389/fmicb.2016.01079](https://doi.org/10.3389/fmicb.2016.01079)

N/A

2016

Adam, E., Groenenboom, A. E., Kurm, V., Rajewska, M., **Schmidt, R.**, Tyc, O., Weidner, S., Berg, G., de Boer, W., & Falcão Salles, J.


### Microbial Small Talk: Volatiles in Fungal-Bacterial Interactions. 
Front Microbiol. [DOI: 10.3389/fmicb.2015.01495](https://doi.org/10.3389/fmicb.2015.01495)

N/A

2016

**Schmidt, R.**, Etalo, D. W., de Jager, V., Gerards, S., Zweers, H., de Boer, W., & Garbeva, P.

### Volatile affairs in microbial interactions. 
ISME J. [DOI: 10.1038/ismej.2015.42](https://doi.org/10.1038/ismej.2015.42)

N/A

2016 

**Schmidt, R.**, Cordovez, V., de Boer, W., Raaijmakers, J., & Garbeva, P.

### Exploring the genomic traits of fungus-feeding bacterial genus *Collimonas*.
BMC Genomics. [DOI: 10.1186/s12864-015-2289-3](https://doi.org/10.1186/s12864-015-2289-3)

N/A 

2015

Song, C., **Schmidt, R.**, de Jager, V., Krzyzanowska, D., Jongedijk, E., Cankar, K., Beekwilder, J., van Veen, A., de Boer, W., van Veen, J. A., & Garbeva, P.

### Effects of bacterial inoculants on the indigenous microbiome and secondary metabolites of chamomile plants. 
Front Microbiol. [DOI: 10.3389/fmicb.2013.00400](doi:10.3389/fmicb.2014.00064)

N/A

2014 

**Schmidt, R.**, Köberl, M., Mostafa, A., Ramadan, E. M., Monschein, M., Jensen, K. B., Bauer, R., & Berg, G. 

### The microbiome of medicinal plants: diversity and importance for plant growth, quality and health.
Front Microbiol. [DOI: 10.3389/fmicb.2014.00064](https://doi.org/10.3389/fmicb.2013.00400)

N/A

2013 

Köberl, M., **Schmidt, R.**, Ramadan, E. M., Bauer, R., & Berg, G.


Manuscripts in preparation {data-icon=file}
--------------------------------------------------------------------------------

### Soil hydrogen enrichment increases H<sub>2</sub>-oxiding bacterial activity and changes microbial community structure and function (under review).
Soil Biol. Biochem.

N/A

N/A

Wang X., **Schmidt R.**, Constant P., & Yergeau E. 

### Nitrapyrin has far reaching effects on the soil microbial community structure, composition, diversity and functions (submitted).
Appl. Environ. Microbiol. 

N/A

N/A

**Schmidt R.**, Wang X., Garbeva, P., & Yergeau E. 

### Infochemicals in terrestrial plants and marine macroalgal holobionts under a changing climate (under review). 
New Phytologist. 

N/A 

N/A 

**Schmidt R.**, & Saha, M.

Press and Outreach (EXCERPT) {data-icon=newspaper}
--------------------------------------------------------------------------------

### [Microbial aromas could save agriculture from climate change.](https://theconversation.com/microbial-aromas-might-save-crops-from-drought-103960)
The Conversation.

N/A

2019

### [The Art of Microbial Communication.](https://www.sciartmagazine.com/the-art-of-microbial-communication.html)
SciArt Magazine. 

N/A

2018

### [World's most spoken language is 'Terpene'.](https://www.sciencedaily.com/releases/2017/04/170413190718.htm)
Science Daily. 

N/A


2017


References upon request {data-icon=user} 
--------------------------------------------------------------------------------





