---
title: "Ruth Schmidt's Resume"
author: Ruth L. Schmidt
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: custom_resume.css
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print

---

```{css, echo=FALSE}
a {
  color: #008B8B;
}

.pagedjs_page:not(:first-of-type) {
  background: white;
}

.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-home"></i> 5932 Avenue de L'Esplanade, H2T3A3 Montréal, Canada
- <i class="fa fa-phone"></i> +1 438-979-8112
- <i class="fa fa-envelope"></i> schmidt.ruth@gmail.com
- <i class="fa fa-linkedin"></i> [linkedin.com/ruth-schmidt/](https://www.linkedin.com/in/ruth-schmidt/)
- <i class="fa fa-globe"></i> [ruthlydiaschmidt.com](https://ruthlydiaschmidt.com/)


Technical Skills {#skills}
--------------------------------------------------------------------------------

- R, Dash & Dash Bio (Plotly), Python, UNIX, Git, Markdown, SQL (basics), CSS & HTML (basics)
- Multivariate statistics, statistical models
- Molecular biology techniques, Omic technologies & data analysis
- Data cleaning, processing, manipulation & visualization

Interpersonal Skills {#skills}
--------------------------------------------------------------------------------

- Excellent communicator (written & verbal)
- Highly creative
- Problem solver
- Strong team player & collaborative
- Good time management
- Open-minded and adaptable

Languages {#skills}
--------------------------------------------------------------------------------

- German (Native)
- English (Fluent)
- Spanish (Advanced)
- French (Beginner) 

Main
================================================================================

Ruth Lydia Schmidt {#title}
--------------------------------------------------------------------------------

### Microbial Ecologist & Data Scientist

A dynamic and resourceful microbial ecologist with 8 years of experience in <br> agricultural microbiome research, data analysis and science communication, strong leadership and a broad set of technical and interpersonal skills. <br> Passionate about finding sustainable solutions for pressing issues of our time through science, data and policy.</br>

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Ph.D. in Microbial Ecology

Wageningen University & Netherlands Institute of Ecology

Wageningen, The Netherlands

2017 

### M.S. in Biotechnology 

Graz University of Technology

Graz, Austria

2012

### M.S. in Molecular Biology 

Graz University of Technology

Graz, Austria

2010

Research Experience {data-icon=flask}
--------------------------------------------------------------------------------

### Mitacs Postdoctoral Fellow

Institut national de la recherche scientifique (INRS) & Plotly 

Montréal, Canada

2020 - Present

- Developing open-source visualization apps for omic data in microbiome research using Ploty’s Dash libraries.
- Research on microbial solutions to drought in agriculture.
- Led lab and field studies with wheat under drought conditions.
- Conducted analysis of omic data (quantitative metagenomics, metatranscriptomics, metabolomics). 

### PhD Candidate 

Netherlands Institute of Ecology & Wageningen University

Wageningen, The Netherlands

2013 - 2018

- Studied microbial secondary metabolites for sustainable agriculture.
- Characterized molecular mechanism underlying volatile interaction in soil microbes using a combination of omic, microbiological, and analytical (GC-MS) approaches.
-	Analyzed omic data (proteomics, metabolomics) and developed workflow for metabolomic data analysis. 
-	Collaborated with international research institutes in Germany, US & Sweden on genomics and proteomics projects.

### Master student and University assistant  

Graz University of Technology

Graz, Austria

2010-2012

- Led and conducted field study on the effect of biocontrol agents in field in Egypt. 
- Performed analysis of 16S rRNA sequencing data & analytical data (LC-MS).
